services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: notebook
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    restart: unless-stopped
    develop:
      watch:
        - action: restart
          path: .
          #target: /app
          ignore:
            - node_modules
            - .next
            - dist
            - out
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo:7
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: